# Generated by Django 6.1.2 on 2026-10-08 09:56

import django.core.validators
import django.db.models.deletion
import imagekit.models.fields
from django.db import migrations, models

import apps.core.fields


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="InfoPage",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("title", models.CharField(max_length=255, verbose_name="Заголовок")),
                ("slug", models.SlugField(blank=True, max_length=255, unique=True, verbose_name="Адрес страницы")),
                ("body", models.TextField(blank=True, verbose_name="Текст")),
                ("is_published", models.BooleanField(default=True, verbose_name="Опубликовано")),
            ],
            options={
                "verbose_name": "Инфо-страница",
                "verbose_name_plural": "Инфо-страницы",
                "ordering": ["title"],
            },
        ),
        migrations.CreateModel(
            name="SiteSettings",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("address", models.CharField(blank=True, max_length=255, verbose_name="Адрес")),
                ("map_url", models.URLField(blank=True, max_length=500, verbose_name="Ссылка на карту")),
                ("vk_url", models.URLField(blank=True, max_length=500, verbose_name="VK")),
                ("home_intro", models.TextField(blank=True, verbose_name="Вступление на главной")),
                ("events_intro", models.TextField(blank=True, verbose_name="Вступление на странице мероприятий")),
                ("about_text", models.TextField(blank=True, verbose_name="О нас")),
                ("philosophy_text", models.TextField(blank=True, verbose_name="Философия")),
                ("nearby_text", models.TextField(blank=True, verbose_name="Что рядом")),
                ("contacts_text", models.TextField(blank=True, verbose_name="Текст на странице контактов")),
                (
                    "contacts_map",
                    imagekit.models.fields.ProcessedImageField(
                        blank=True,
                        upload_to=apps.core.fields.UploadTo("site"),
                        validators=[apps.core.fields.validate_image_upload],
                        verbose_name="Карта на странице контактов",
                    ),
                ),
                (
                    "about_map",
                    imagekit.models.fields.ProcessedImageField(
                        blank=True,
                        upload_to=apps.core.fields.UploadTo("site"),
                        validators=[apps.core.fields.validate_image_upload],
                        verbose_name="Карта на странице «О нас»",
                    ),
                ),
            ],
            options={
                "verbose_name": "Настройки сайта",
                "verbose_name_plural": "Настройки сайта",
            },
        ),
        migrations.CreateModel(
            name="Phone",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "number",
                    models.CharField(
                        max_length=10,
                        validators=[
                            django.core.validators.RegexValidator(
                                "^\\d{10}$", "10 цифр без +7 и 8, например 9029856594."
                            )
                        ],
                        verbose_name="Номер",
                    ),
                ),
                ("order", models.PositiveIntegerField(db_index=True, default=0, verbose_name="Порядок")),
                ("is_whatsapp", models.BooleanField(default=False, verbose_name="WhatsApp")),
                ("is_telegram", models.BooleanField(default=False, verbose_name="Telegram")),
                (
                    "settings",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="phones", to="core.sitesettings"
                    ),
                ),
            ],
            options={
                "verbose_name": "Телефон",
                "verbose_name_plural": "Телефоны",
                "ordering": ["order", "id"],
                "constraints": [
                    models.UniqueConstraint(
                        condition=models.Q(("is_whatsapp", True)), fields=("settings",), name="one_whatsapp_phone"
                    ),
                    models.UniqueConstraint(
                        condition=models.Q(("is_telegram", True)), fields=("settings",), name="one_telegram_phone"
                    ),
                ],
            },
        ),
    ]
