# Generated by Django 6.1.2 on 2026-10-08 18:20

import apps.core.maps
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='map_embed_url',
            field=apps.core.maps.MapEmbedURLField(blank=True, help_text='В Яндекс Картах: «Поделиться» → «Встроить карту» → скопируйте код и вставьте сюда целиком.', max_length=1000, verbose_name='Яндекс Карта на странице контактов'),
        ),
    ]
