# Generated by Django 6.1.2 on 2026-10-08 20:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_sitesettings_map_embed_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sitesettings',
            name='about_map',
        ),
        migrations.RemoveField(
            model_name='sitesettings',
            name='contacts_map',
        ),
        migrations.RemoveField(
            model_name='sitesettings',
            name='map_url',
        ),
    ]
