# Generated by Django 6.1.2 on 2026-10-08 20:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_remove_map_url_and_map_images'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='reviews_url',
            field=models.URLField(blank=True, help_text='Страница отзывов о Т-Парке: кнопки «Все отзывы» и «Оставить отзыв» на странице отзывов.', max_length=500, verbose_name='Отзывы на Яндекс Картах'),
        ),
    ]
