# Generated by Django 6.1.2 on 2026-10-09 07:38

import apps.core.fields
import django.core.validators
import imagekit.models.fields
from django.db import migrations, models


PARK_ADDRESS = "Калужская область, Жуковский район, село Восход"


def fill_empty_address(apps, schema_editor):
    apps.get_model("core", "SiteSettings").objects.filter(address="").update(address=PARK_ADDRESS)


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_reviews_polish'),
    ]

    operations = [
        migrations.AddField(
            model_name='infopage',
            name='seo_description',
            field=models.CharField(blank=True, help_text='Лучше 120–160 символов: это текст под ссылкой в выдаче. Пусто — начало текста страницы.', max_length=300, verbose_name='Описание для поисковиков (description)'),
        ),
        migrations.AddField(
            model_name='infopage',
            name='seo_title',
            field=models.CharField(blank=True, help_text='До 60–70 символов, выводится как есть. Пусто — «Название — Т-Парк, Калужская область».', max_length=70, verbose_name='Заголовок для поисковиков (title)'),
        ),
        migrations.AddField(
            model_name='infopage',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Изменено'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='address_locality',
            field=models.CharField(blank=True, default='Жуковский район, село Восход', max_length=128, verbose_name='Населённый пункт'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='address_region',
            field=models.CharField(blank=True, default='Калужская область', max_length=128, verbose_name='Регион'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='google_verification',
            field=models.CharField(blank=True, max_length=128, verbose_name='Код подтверждения Google Search Console'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='latitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, verbose_name='Широта'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='longitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, verbose_name='Долгота'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='og_image',
            field=imagekit.models.fields.ProcessedImageField(blank=True, help_text='Показывается в превью ссылки в VK, Telegram и мессенджерах, если у страницы нет своего фото. Лучше горизонтальная, 1200×630.', upload_to=apps.core.fields.UploadTo('seo'), validators=[apps.core.fields.validate_image_upload], verbose_name='Картинка для соцсетей'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='opening_hours',
            field=models.CharField(blank=True, help_text='В формате schema.org, например: Mo-Su 09:00-21:00.', max_length=128, verbose_name='Часы работы'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='postal_code',
            field=models.CharField(blank=True, max_length=6, verbose_name='Индекс'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='price_range',
            field=models.CharField(blank=True, help_text='Например: ₽₽ или 500–5000 ₽.', max_length=32, verbose_name='Уровень цен'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='seo_about_description',
            field=models.CharField(blank=True, max_length=300, verbose_name='О нас: description'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='seo_about_title',
            field=models.CharField(blank=True, max_length=70, verbose_name='О нас: title'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='seo_contacts_description',
            field=models.CharField(blank=True, max_length=300, verbose_name='Контакты: description'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='seo_contacts_title',
            field=models.CharField(blank=True, max_length=70, verbose_name='Контакты: title'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='seo_events_description',
            field=models.CharField(blank=True, max_length=300, verbose_name='Мероприятия: description'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='seo_events_title',
            field=models.CharField(blank=True, max_length=70, verbose_name='Мероприятия: title'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='seo_gallery_description',
            field=models.CharField(blank=True, max_length=300, verbose_name='Галерея: description'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='seo_gallery_title',
            field=models.CharField(blank=True, max_length=70, verbose_name='Галерея: title'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='seo_home_description',
            field=models.CharField(blank=True, max_length=300, verbose_name='Главная: description'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='seo_home_title',
            field=models.CharField(blank=True, max_length=70, verbose_name='Главная: title'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='seo_reviews_description',
            field=models.CharField(blank=True, max_length=300, verbose_name='Отзывы: description'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='seo_reviews_title',
            field=models.CharField(blank=True, max_length=70, verbose_name='Отзывы: title'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='seo_title_suffix',
            field=models.CharField(blank=True, default='Т-Парк, Калужская область', help_text='Добавляется к названию страницы: «Сплавы — Т-Парк, Калужская область».', max_length=64, verbose_name='Окончание заголовков'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='street_address',
            field=models.CharField(blank=True, max_length=255, verbose_name='Улица, дом'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='yandex_maps_url',
            field=models.URLField(blank=True, help_text='Ссылка на карточку организации: поисковики свяжут сайт с карточкой, её рейтингом и отзывами.', max_length=500, verbose_name='Т-Парк на Яндекс Картах'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='yandex_metrika_id',
            field=models.CharField(blank=True, max_length=16, validators=[django.core.validators.RegexValidator('^\\d+$', 'Только цифры номера счётчика.')], verbose_name='Номер счётчика Яндекс Метрики'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='yandex_verification',
            field=models.CharField(blank=True, help_text='Из мета-тега: content="…". Регион сайта (Калужская область) задаётся в Вебмастере: «Информация о сайте» → «Региональность».', max_length=64, verbose_name='Код подтверждения Яндекс Вебмастера'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='address',
            field=models.CharField(blank=True, default='Калужская область, Жуковский район, село Восход', max_length=255, verbose_name='Адрес'),
        ),
        migrations.RunPython(fill_empty_address, migrations.RunPython.noop),
    ]
