# Generated by Django 6.1.2 on 2026-10-09 10:44

import apps.core.fields
import django.db.models.deletion
import imagekit.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_seo'),
        ('core', '0007_rename_philosophy_text_founder_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='about_motto',
            field=models.CharField(blank=True, default='Красивое место, интересные люди, запоминающееся приключение — вот формула ожидаемой реальности.', help_text='Одна фраза крупным шрифтом в начале страницы.', max_length=255, verbose_name='Цитата в шапке'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='about_photo',
            field=imagekit.models.fields.ProcessedImageField(blank=True, help_text='Лучше горизонтальное: парк, лес, река, люди.', upload_to=apps.core.fields.UploadTo('about'), validators=[apps.core.fields.validate_image_upload], verbose_name='Фото в шапке'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='founder_lead',
            field=models.CharField(blank=True, default='Этот человек придумал и создал Т-Парк', max_length=255, verbose_name='Основатель: подзаголовок'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='founder_name',
            field=models.CharField(blank=True, default='Дмитрий Сергеев', max_length=128, verbose_name='Основатель: имя'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='founder_photo',
            field=imagekit.models.fields.ProcessedImageField(blank=True, help_text='Портрет, лучше вертикальный.', upload_to=apps.core.fields.UploadTo('about'), validators=[apps.core.fields.validate_image_upload], verbose_name='Основатель: фото'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='safety_page',
            field=models.ForeignKey(blank=True, help_text='Инфо-страница, на которую ведёт плашка «Правила безопасности» на странице «О нас».', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='core.infopage', verbose_name='Правила безопасности'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='founder_text',
            field=models.TextField(blank=True, help_text='Регалии и роли — удобнее списком.', verbose_name='Основатель: о нём'),
        ),
        migrations.CreateModel(
            name='FounderFact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(help_text='Например: 1000+.', max_length=16, verbose_name='Число')),
                ('label', models.CharField(help_text='Например: тренингов провёл.', max_length=128, verbose_name='Подпись')),
                ('order', models.PositiveIntegerField(db_index=True, default=0, verbose_name='Порядок')),
                ('settings', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='founder_facts', to='core.sitesettings')),
            ],
            options={
                'verbose_name': 'Цифра',
                'verbose_name_plural': 'Основатель в цифрах (О нас)',
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='ParkFormat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Например: T-park.', max_length=32, verbose_name='Название')),
                ('caption', models.CharField(help_text='Например: тренинг-парк.', max_length=128, verbose_name='Подпись')),
                ('description', models.CharField(blank=True, help_text='Одна-две фразы, необязательно.', max_length=255, verbose_name='Описание')),
                ('order', models.PositiveIntegerField(db_index=True, default=0, verbose_name='Порядок')),
                ('category', models.ForeignKey(blank=True, help_text='Карточка станет ссылкой, если категория опубликована.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='catalog.category', verbose_name='Ссылка на категорию')),
                ('settings', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='park_formats', to='core.sitesettings')),
            ],
            options={
                'verbose_name': 'Формат',
                'verbose_name_plural': 'Форматы (О нас)',
                'ordering': ['order', 'id'],
            },
        ),
    ]
