# Generated by Django 6.1.2 on 2026-10-09 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_about_defaults'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='home_show_events',
            field=models.BooleanField(default=True, help_text='Блок появляется, только если есть предстоящие мероприятия.', verbose_name='Ближайшие мероприятия на главной'),
        ),
    ]
