# Generated by Django 6.1.2 on 2026-10-08 09:57

import apps.core.fields
import django.core.validators
import imagekit.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(db_index=True, default=0, verbose_name='Порядок')),
                ('name', models.CharField(max_length=128, verbose_name='Имя')),
                ('position', models.CharField(blank=True, max_length=128, verbose_name='Должность')),
                ('photo', imagekit.models.fields.ProcessedImageField(blank=True, upload_to=apps.core.fields.UploadTo('employees'), validators=[apps.core.fields.validate_image_upload], verbose_name='Фото')),
            ],
            options={
                'verbose_name': 'Сотрудник',
                'verbose_name_plural': 'Сотрудники',
                'ordering': ['order', 'id'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=128, verbose_name='Заголовок')),
                ('date', models.DateField(verbose_name='Дата')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('link', models.URLField(blank=True, help_text='Соцсеть или сайт мероприятия.', max_length=500, verbose_name='Ссылка')),
                ('text_color', models.CharField(blank=True, help_text='Необязательно. По умолчанию белый.', max_length=7, validators=[django.core.validators.RegexValidator('^#[0-9a-fA-F]{6}$', 'Цвет в формате #RRGGBB.')], verbose_name='Цвет текста на фото')),
                ('show_after_date', models.BooleanField(default=False, verbose_name='Показывать после даты')),
                ('image', imagekit.models.fields.ProcessedImageField(blank=True, upload_to=apps.core.fields.UploadTo('events'), validators=[apps.core.fields.validate_image_upload], verbose_name='Фото')),
            ],
            options={
                'verbose_name': 'Мероприятие',
                'verbose_name_plural': 'Мероприятия',
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='GalleryPhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(db_index=True, default=0, verbose_name='Порядок')),
                ('image', imagekit.models.fields.ProcessedImageField(upload_to=apps.core.fields.UploadTo('gallery'), validators=[apps.core.fields.validate_image_upload], verbose_name='Фото')),
                ('caption', models.CharField(blank=True, max_length=255, verbose_name='Подпись')),
            ],
            options={
                'verbose_name': 'Фото галереи',
                'verbose_name_plural': 'Галерея',
                'ordering': ['order', 'id'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Partner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(db_index=True, default=0, verbose_name='Порядок')),
                ('name', models.CharField(blank=True, max_length=128, verbose_name='Название')),
                ('link', models.URLField(blank=True, max_length=500, verbose_name='Ссылка')),
                ('logo', imagekit.models.fields.ProcessedImageField(blank=True, upload_to=apps.core.fields.UploadTo('partners'), validators=[apps.core.fields.validate_image_upload], verbose_name='Логотип')),
            ],
            options={
                'verbose_name': 'Партнёр',
                'verbose_name_plural': 'Партнёры',
                'ordering': ['order', 'id'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(db_index=True, default=0, verbose_name='Порядок')),
                ('author', models.CharField(max_length=128, verbose_name='Имя')),
                ('text', models.TextField(blank=True, verbose_name='Текст')),
                ('photo', imagekit.models.fields.ProcessedImageField(blank=True, upload_to=apps.core.fields.UploadTo('reviews'), validators=[apps.core.fields.validate_image_upload], verbose_name='Фото')),
                ('is_published', models.BooleanField(default=True, verbose_name='Опубликовано')),
            ],
            options={
                'verbose_name': 'Отзыв',
                'verbose_name_plural': 'Отзывы',
                'ordering': ['order', 'id'],
                'abstract': False,
            },
        ),
    ]
