# Generated by Django 6.1.2 on 2026-10-08 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0002_event_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='date',
            field=models.DateField(blank=True, null=True, verbose_name='Дата отзыва'),
        ),
        migrations.AddField(
            model_name='review',
            name='link',
            field=models.URLField(blank=True, help_text='Например, на отзыв в Яндекс Картах: по клику на карточку.', max_length=500, verbose_name='Ссылка на отзыв'),
        ),
    ]
