# Generated by Django 6.1.2 on 2026-10-08 20:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0003_review_link_date'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Employee',
        ),
    ]
