# Generated by Django 6.1.2 on 2026-10-08 20:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0004_delete_employee'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='author',
            field=models.CharField(blank=True, help_text='Можно не указывать — на сайте будет «Гость Т-Парка».', max_length=128, verbose_name='Имя'),
        ),
    ]
