# Generated by Django 6.1.2 on 2026-10-08 20:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0005_reviews_polish'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='review',
            options={'ordering': [models.OrderBy(models.F('date'), descending=True, nulls_last=True), '-id'], 'verbose_name': 'Отзыв', 'verbose_name_plural': 'Отзывы'},
        ),
        migrations.RemoveField(
            model_name='review',
            name='order',
        ),
        migrations.AlterField(
            model_name='review',
            name='link',
            field=models.URLField(blank=True, help_text='Например, на отзыв в Яндекс Картах: открывается по клику на подпись источника под отзывом.', max_length=500, verbose_name='Ссылка на отзыв'),
        ),
    ]
