# Generated by Django 6.1.2 on 2026-10-09 06:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0006_review_order_by_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='review',
            name='author',
        ),
    ]
