# Generated by Django 6.1.2 on 2026-10-09 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0007_remove_review_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='seo_description',
            field=models.CharField(blank=True, help_text='Лучше 120–160 символов: это текст под ссылкой в выдаче. Пусто — начало текста страницы.', max_length=300, verbose_name='Описание для поисковиков (description)'),
        ),
        migrations.AddField(
            model_name='event',
            name='seo_title',
            field=models.CharField(blank=True, help_text='До 60–70 символов, выводится как есть. Пусто — «Название — Т-Парк, Калужская область».', max_length=70, verbose_name='Заголовок для поисковиков (title)'),
        ),
        migrations.AddField(
            model_name='event',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Изменено'),
        ),
    ]
