# Generated by Django 6.1.2 on 2026-10-09 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0008_seo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='text_color',
        ),
        migrations.AddField(
            model_name='event',
            name='end_date',
            field=models.DateField(blank=True, help_text='Только для многодневных: «с 18 ноября по 17 декабря».', null=True, verbose_name='Дата окончания'),
        ),
        migrations.AddField(
            model_name='event',
            name='price',
            field=models.CharField(blank=True, help_text='Коротко: «1000 ₽ с участника», «Бесплатно».', max_length=100, verbose_name='Стоимость'),
        ),
        migrations.AddField(
            model_name='event',
            name='start_time',
            field=models.TimeField(blank=True, null=True, verbose_name='Время начала'),
        ),
    ]
