# Generated by Django 6.1.2 on 2026-10-08 09:56

import apps.core.fields
import django.db.models.deletion
import imagekit.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(db_index=True, default=0, verbose_name='Порядок')),
                ('name', models.CharField(max_length=128, verbose_name='Название')),
                ('slug', models.SlugField(blank=True, max_length=255, unique=True, verbose_name='Адрес страницы')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('preview', imagekit.models.fields.ProcessedImageField(blank=True, upload_to=apps.core.fields.UploadTo('catalog/previews'), validators=[apps.core.fields.validate_image_upload], verbose_name='Превью для главной')),
                ('is_published', models.BooleanField(default=False, verbose_name='Опубликовано')),
            ],
            options={
                'verbose_name': 'Категория',
                'verbose_name_plural': 'Категории',
                'ordering': ['order', 'id'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, verbose_name='Название')),
                ('slug', models.SlugField(blank=True, max_length=255, unique=True, verbose_name='Адрес страницы')),
                ('short_description', models.TextField(blank=True, verbose_name='Краткое описание')),
                ('description', models.TextField(blank=True, verbose_name='Полное описание')),
                ('price', models.CharField(blank=True, help_text='Например: 1500 или «договорная».', max_length=32, verbose_name='Цена')),
                ('price_unit', models.CharField(blank=True, help_text='Например: час, сутки, человек.', max_length=128, verbose_name='За что')),
                ('is_published', models.BooleanField(default=True, verbose_name='Опубликовано')),
                ('has_page', models.BooleanField(default=False, help_text='Карточка в категории ведёт на страницу услуги.', verbose_name='Отдельная страница')),
            ],
            options={
                'verbose_name': 'Услуга',
                'verbose_name_plural': 'Услуги',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='CategoryGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(db_index=True, default=0, verbose_name='Порядок')),
                ('name', models.CharField(max_length=128, verbose_name='Название')),
                ('categories', models.ManyToManyField(blank=True, related_name='groups', to='catalog.category', verbose_name='Категории')),
            ],
            options={
                'verbose_name': 'Группа категорий',
                'verbose_name_plural': 'Группы категорий',
                'ordering': ['order', 'id'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='CategoryPhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(db_index=True, default=0, verbose_name='Порядок')),
                ('image', imagekit.models.fields.ProcessedImageField(upload_to=apps.core.fields.UploadTo('catalog/categories'), validators=[apps.core.fields.validate_image_upload], verbose_name='Фото')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='catalog.category')),
            ],
            options={
                'verbose_name': 'Фото категории',
                'verbose_name_plural': 'Фото категории',
                'ordering': ['order', 'id'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ServicePhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(db_index=True, default=0, verbose_name='Порядок')),
                ('image', imagekit.models.fields.ProcessedImageField(upload_to=apps.core.fields.UploadTo('catalog/services'), validators=[apps.core.fields.validate_image_upload], verbose_name='Фото')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='catalog.service')),
            ],
            options={
                'verbose_name': 'Фото услуги',
                'verbose_name_plural': 'Фото услуги',
                'ordering': ['order', 'id'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='CategoryService',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(db_index=True, default=0, verbose_name='Порядок')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='service_links', to='catalog.category', verbose_name='Категория')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='category_links', to='catalog.service', verbose_name='Услуга')),
            ],
            options={
                'verbose_name': 'Услуга в категории',
                'verbose_name_plural': 'Услуги в категории',
                'ordering': ['order', 'id'],
                'abstract': False,
                'unique_together': {('category', 'service')},
            },
        ),
    ]
